myfav/config/routes.rb
Rails.application.routes.draw do
controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
root to: 'favorites#index'
  resources :users
  resources :favorites
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

myfav/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

myfav/app/models/favorite.rb
class Favorite < ApplicationRecord
	validates :name, :birthplace, :height, :category, :link, :comment,:image, presence: true
	validates :MBTI, inclusion: {in: ['ESTP','ISTP','ESTJ','ISTJ','ESFJ','ISFJ','ESFP','ISFP','ENTJ','INTJ','ENTP','INTP','ENFJ','INFJ','ENFP','INFP']}, allow_blank: true
	validates :bloodtype, inclusion: {in: ['A','B','O','AB']}, allow_blank: true
	validates :age, :height, :weight, numericality: true, allow_blank: true
	validates :gender, inclusion: {in: ['male','female']}, allow_blank: true
	belongs_to :user
	has_many :likes, dependent: :destroy
	mount_uploader :image, ImageUploader
	has_one_attached :image
	def favorited?(user)
   likes.where(user_id: user.id).exists?
end
	
	
	
end

myfav/app/models/like.rb
class Like < ApplicationRecord
belongs_to :user
belongs_to :favorite
end

myfav/app/models/user.rb
class User < ApplicationRecord
#devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
  has_secure_password
  has_many :favorites,dependent: :destroy
  has_many :likes,dependent: :destroy
  
  validates :username, presence: true
  validates :name, presence: true
  validates :email, presence: true
  validates :username, uniqueness: true
  
  def liked_by?(favorite_id)
  likes.where(favorite_id: favorite_id).exists?  
end
  
end

myfav/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  
  private
  def require_login
    unless logged_in?
	
	  flash[:error] = "ログインが必要です。"
      redirect_to(login_url)
    end
	end
	
	def logged_in?
    session[:user_id].present?
  end
end

myfav/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[ show edit update destroy ]
skip_before_action :require_login, only: [:index, :show]

  # GET /favorites or /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1 or /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites or /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully created." }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1 or /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully updated." }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1 or /favorites/1.json
  def destroy
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Favorite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:name, :nickname, :birthday, :bloodtype, :birthplace, :office, :age, :gender, :height, :weight, :category, :MBTI, :link, :comment, :image, :caption,:user_id)
    end
end

myfav/app/controllers/likes_controller.rb
class LikesController < ApplicationController
end
class LikesController < ApplicationController
  def create
    Like.create(user_id: session[:user_id], favorite_id: params[:id])
    redirect_to favorites_path
  end
  def destroy
    Like.find_by(user_id: session[:user_id], favorite_id: params[:id]).destroy
    redirect_to favorites_path
  end
end

myfav/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
session[:user_id] = nil
  end

  def create
   @user = User.find_by(username: params[:username])
  if @user && @user.authenticate(params[:password])
    session[:user_id] = @user.id
	flash[:notice] = "正常にログインできました。"
    redirect_to(favorites_url)
  else
    flash[:alert] = "ログインネームまたはパスワードが間違っています"
	redirect_to(login_url)
  end

  end

  def destroy
  session[:user_id] = nil
  flash[:notice] = "ログアウトしました。"
  redirect_to(favorites_url)
  end


  
end

myfav/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
	skip_before_action :require_login, only: [:new,:create,:show]
	
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
    end
end

myfav/app/helpers/application_helper.rb
module ApplicationHelper
 require "uri"

  def text_url_to_link text

    URI.extract(text, ['http','https']).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

      text.gsub!(url, sub_text)
    end

    return text
  end
end

myfav/app/helpers/favorites_helper.rb
module FavoritesHelper
end

myfav/app/helpers/likes_helper.rb
module LikesHelper
end

myfav/app/views/favorites/_favorite.html.erb
<div id="<%= dom_id favorite %>">
<div class="favorites">
<p>
    <strong>User:</strong>
    <%= favorite.user_id %>:
	 <% if favorite.user %>
            <%= favorite.user.username %>
        <% else %>
            User not found
        <% end %>
        
  </p>
  <hr>
  <p>
    <strong>Name:</strong>
    <%= favorite.name %>
  </p>
    <p>
    <strong>Image:</strong><br>
	<% if @favorite.image.present? %>
	<div class="photo">
 <%= image_tag @favorite.image.url %>
  </div>
  <% else %>
  <div class="photo">
  <%= image_tag 'people_team.png' %>
  </div>

<% end %>

   
  </p>
  <p>
    <strong>Source:</strong>
	 </p>
	 <div class="link">
    <%= text_url_to_link((h(favorite.caption).html_safe)).html_safe %>
 </div>

  <p>
    <strong>Fullname/Nickname:</strong>
    <%= favorite.nickname %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= favorite.birthday %>
  </p>

  <p>
    <strong>Bloodtype:</strong>
    <%= favorite.bloodtype %>
  </p>

  <p>
    <strong>Birthplace:</strong>
    <%= favorite.birthplace %>
  </p>

  <p>
    <strong>Office:</strong>
    <%= favorite.office %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= favorite.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= favorite.gender %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= favorite.height %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= favorite.weight %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= favorite.category %>
  </p>

  <p>
    <strong>MBTI:</strong>
    <%= favorite.MBTI %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= text_url_to_link((h(favorite.link).html_safe)).html_safe %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= favorite.comment %>
  </p>
  </div>

</div>

myfav/app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <% if favorite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
   <div>
  <%= form.label :image, style: "display: block" %>
 <%= form.file_field :image, class: "image" %>
   </div>
   <div>
  <%= form.label :caption, style: "display: block" %>
 <%= form.text_field :caption %>
   </div>
  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  Fullname/
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.label :bloodtype, style: "display: block" %>
    <%= form.text_field :bloodtype %>
  </div>

  <div>
    <%= form.label :birthplace, style: "display: block" %>
    <%= form.text_field :birthplace %>
  </div>

  <div>
    <%= form.label :office, style: "display: block" %>
    <%= form.text_field :office %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.number_field :height %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :MBTI, style: "display: block" %>
    <%= form.text_field :MBTI %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_area :link %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

myfav/app/views/favorites/_like.html.erb
<td><%= link_to 'Like', favorite_likes_path(favorite_id: favorite.id), method: :post%></td>

myfav/app/views/favorites/_like_button.html.erb
<% if User.find(session[:user_id]).like?(favorite) %>
 <%= render 'unlike', { favorite:favorite } %>
<% else %>
 <%= render 'like', { favorite: favorite } %>
<% end %>

myfav/app/views/favorites/_unlike.html.erb
<td><%= link_to 'UnLike', favorite_like_path(favorite_id: favorite.id, id: User.find(session[:user_id]).likes.find_by(favorite_id: favorite.id)), method: :delete %></td>

myfav/app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render "form", favorite: @favorite %>

<br>

<div>
  <%= link_to "Show this favorite", @favorite %> |
  <%= link_to "Back to favorites", favorites_path %>
</div>

myfav/app/views/favorites/index.html.erb
<% content_for :css do %>
	<%= stylesheet_link_tag "fav_index" %>
<% end %>
<p style="color: green"><%= notice %></p>

<h1>Favorites</h1>

<div class="favorites">
  <% @favorites.each do |favorite| %>
    <div>
	<div class="fav_name">
    <h2><%= favorite.name %></h2>
	</div>
    
	
	<p>
    <strong>Image:</strong><br>
	<% if favorite.image.present? %>
	<div class="photo">
 <%= image_tag favorite.image.url %>
 </div>
  <% else %>
  <div class="photo">
  <%= image_tag 'people_team.png' %>
  </div>
<% end %> 
  </p>
  
	
	
	<p>
	<strong>Source:</strong>
	</p>
	<div class="link">
	<%= text_url_to_link((h(favorite.caption).html_safe)).html_safe %>
	</div>
	
	
  
<% session[:user_id] && if User.find(session[:user_id]).liked_by?(favorite.id) %>
  <%= form_with(model: favorite, url: destroy_like_path(favorite), method: :delete, local: true) do |form| %>
    <%= form.submit '💖' %><%= favorite.likes.count %>
  <% end %>
<% else %>
  <%= form_with(model: favorite, url: create_like_path(favorite), method: :post, local: true) do |form| %>
    <%= form.submit '♡' %><%= favorite.likes.count %>
  <% end %>
  <% end %>
  
    <p>
      <%= link_to "Show this favorite", favorite %>
    </p>
	<hr>
  <% end %>
  </div>
</div>




<%= link_to "New favorite", new_favorite_path %>

myfav/app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render "form", favorite: @favorite %>

<br>

<div>
  <%= link_to "Back to favorites", favorites_path %>
</div>

myfav/app/views/favorites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @favorite %>





<div>
  <%= link_to "Edit this favorite", edit_favorite_path(@favorite) %> |
  <%= link_to "Back to favorites", favorites_path %>

  <%= button_to "Destroy this favorite", @favorite, method: :delete %>
</div>

myfav/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfav</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
	<%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_importmap_tags %>
	
  </head>

  <body>
<% if session[:user_id].present? %>
		  <p><%=User.find(session[:user_id]).username%>としてログインしています</p>
            <%= button_to "ログアウト", logout_path, method: :delete %>
          
<% else %>
            <%= link_to "ログイン", login_path%>
			<%= link_to "新規登録", new_user_path%>

<% end %>
    <%= yield %>
  </body>
</html>

myfav/app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :favorite_id, style: "display: block" %>
    <%= form.number_field :favorite_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

myfav/app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
  <p>
    <strong>User:</strong>
    <%= like.user_id %>
  </p>

  <p>
    <strong>Favorite:</strong>
    <%= like.favorite_id %>
  </p>
  
  <% if favorite.liked_by?(current_user) %>
	<%= link_to(favorite_unlike_path(favorite), method: :delete) do %>
		<p>いいね解除</p>
	<% end %>
  <% else %>
	<%= link_to(favorite_like_path(favorite), method: :post) do %>
		<p>いいね</p>
	<% end %>
  <% end %>

</div>

myfav/app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

myfav/app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

myfav/app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

myfav/app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render 'like'%>

<div>
  <%#= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

myfav/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

myfav/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

myfav/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

myfav/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

myfav/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

myfav/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>